AWSTemplateFormatVersion: 2010-09-09
Description: >-
  notification

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  SnsArn:
    Type: String
  DebugEnabled:
    Type: String
    Default: 'true'

Resources:
  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "devops-notifications"
      Handler: src/handlers/index.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Send a notification using the body.payload
      Environment:
        Variables:
          DEBUG: !Ref DebugEnabled
          SNS_ARN: !Ref SnsArn
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/SendNotifications'
