name: Continuous Integration

on:
  push:
    branches:
      - feature/*
      - bugfix/*
    paths:
      - globals/**
      - lib/**
      - liquibase/**
      - src/**
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  backend_continuous_integration:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install project dependencies
        run: npm ci

      - name: Run Linter (ignore failure, Feature Push)
        if: github.head_ref == ''
        continue-on-error: true
        run: npm run lint

      - name: Run Linter (From Pull Request)
        if: github.head_ref != ''
        continue-on-error: false
        run: npm run lint

      - name: Run Audit
        run: npm audit --production

      - name: Run Tests
        run: npm run test
